// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaFNL1CNH-qmnmRPljycEi9IV5E0zk9_M',
    appId: '1:224453464154:web:147a8e4d602001804fc863',
    messagingSenderId: '224453464154',
    projectId: 'wintelchin',
    authDomain: 'wintelchin.firebaseapp.com',
    storageBucket: 'wintelchin.firebasestorage.app',
    measurementId: 'G-4WGB3HTMT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbPyWlLZeAtMcjz9-k27Q0c7lrd6hSErY',
    appId: '1:224453464154:android:0e2b6253f28afdcf4fc863',
    messagingSenderId: '224453464154',
    projectId: 'wintelchin',
    storageBucket: 'wintelchin.firebasestorage.app',
  );
}
